### ISSUE TITLE
Binary release including the textual 7.10 changes

### ISSUE THREAD

**Issue by karlsander** [rectalogic/TextualSlack#1]
I tried to build it myself, but stumbled into some trouble that I can maybe resolve or report separately, but If it isn't too much effort it would be great if you could create a new binary release that includes the latest commits.

**Comment by rectalogic** [comment]
Yeah it no longer builds with current xcode due to a SlackKit bug https://github.com/pvzig/SlackKit/issues/133

**Comment by rectalogic** [comment]
Published a new release https://github.com/rectalogic/TextualSlack/releases/tag/v6-1.1.4
